export const navData=[
    {
        path:"/",
        xs:2,
        label:"Home"
    },
    {
        path:"about",
        xs:2,
        label:"About"
    },
    {
        path:"/contact",
        xs:2,
        label:"Contact"
    },
    {
        path:"/product",
        xs:2,
        label:"Product"
    }
]